source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
target "FirstApp" do
  pod 'SVProgressHUD', '1.1.3'
  pod 'Masonry', '0.6.3'
  pod 'dsBridge', '2.0.2'
  pod 'AFNetworking', '3.0.4'
  pod 'SDWebImage', '~> 4.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'dsBridge'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '7.0'
      end
    end
  end
end


